version: '3.8'
services:
  ################################## USUARIS ##################################
  ################################## ALBERT  ##################################
  albert_presence:
  # podria ficar: "build: \n\t context: users/Albert
    build: ./sensors/presence
    command: python3 -u presencesensor.py
    #maybe no fa falta depends on
    depends_on:
      - albert_mqtt
      - kafka
    restart: on-failure:10

  albert_temp:
    build: ./sensors/temperature
    command: python3 -u temperaturesensor.py
    depends_on:
      - albert_mqtt
      - kafka
    restart: on-failure:10

  # albert_light:
  # albert_heat:
  # albert_gateway:
  albert_mqtt:
    image: eclipse-mosquitto:latest
    volumes:
    - ./config:/mosquitto/config/
    ports: 
    - 1883:1883
    restart: on-failure:10

  albert_gateway:
    build: ./gateway
    command: python3 -u gateway.py
    depends_on:
      - albert_mqtt
      - kafka
    environment:
      - BROKER=albert_mqtt
    restart: on-failure:20 #aixo abans era necessari ara crec que no ns pk

  #falten dos persones
  ##################################  MICROSERVEIS  ##################################

  cloud_save:
    build: ./cloud/save
    command: python3 -u save.py
    depends_on:
      - kafka
      - albert_gateway
    restart: on-failure:10 
  ################################## COSES DE KAFKA ##################################
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: yes 
      ADMIN_ENABLE_SERVER: no
      ZOO_LOG_LEVEL: WARN #perque calli una mica si volem tot INFO


  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092

    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT : zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      ALLOW_ANONYMOUS_LOGIN: yes
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      #TOPIC_AUTO_CREATE: False
    depends_on:
      - zookeeper
    
      ################################## INFLUXDB ##################################

  influxdb:
    image: influxdb:latest
    ports:
    - 8086:8086
    environment: 
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: damie
      DOCKER_INFLUXDB_INIT_PASSWORD: pollagorda69 # TODO: canviar si se te por a l'exit 
      DOCKER_INFLUXDB_INIT_ORG: computacio
      DOCKER_INFLUXDB_INIT_BUCKET: computaciobucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: s2d3rf67ren42i0gg666er9
      DOCKER_INFLUXDB_HOSTNAME: influxdb
      DOCKER_INFLUXDB_REPORTING_DISABLED: 'true' #potser no fan falta
      DOCKER_INFLUXDB_BIND_ADDRESS: 0.0.0.0:8086 #potser no fan falta

volumes:
  config: