version: '3.8'
services:
  albert:
  # podria ficar: "build: \n\t context: users/Albert
    build: ./users/albert
    depends_on:
      - mqtt
      - kafka

  #falten dos persones

  #imatges aleatories de moment
  kafka:
    image: wurstmeister/kafka

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"