version: '3.8'
services:
  # albert:
  albert_presence:
  # podria ficar: "build: \n\t context: users/Albert
    build: ./sensors/presence
    command: python3 -u presencesensor.py
    #maybe no fa falta depends on
    depends_on:
      - albert_mqtt
      - kafka
  albert_temp:
    build: ./sensors/temperature
    command: python3 -u temperaturesensor.py
    depends_on:
      - albert_mqtt
      - kafka
  # albert_light:
  # albert_heat:
  # albert_gateway:
  albert_mqtt:
    image: eclipse-mosquitto:latest
    volumes:
    - ./config:/mosquitto/config/

  #falten dos persones

  #imatges aleatories de moment
  kafka:
    image: wurstmeister/kafka

  # mqtt:
  #   image: eclipse-mosquitto:latest
  #   volumes:
  #     - ./config:/mosquitto/config/

volumes:
  config: