version: '3.8'
services:
  ################################## USUARIS ##################################
  ################################## ALBERT  ##################################
  albert_presence:
  # podria ficar: "build: \n\t context: users/Albert
    build: ./albert/sensors/presence
    command: python3 -u presencesensor.py
    #maybe no fa falta depends on
    depends_on:
      - albert_mqtt
      - kafka
    restart: on-failure:10

  albert_temp:
    build: ./albert/sensors/temperature
    command: python3 -u temperaturesensor.py
    depends_on:
      - albert_mqtt
      - kafka
    restart: on-failure:10

  ###ACTUADORS:
  albert_light:
    build: ./albert/actuators/light
    command: python3 -u lightbulb.py
    depends_on:
      - albert_mqtt
    restart: on-failure:10

  albert_heat:
    build: ./albert/actuators/heat
    command: python3 -u heatpump.py
    depends_on:
      - albert_mqtt
    restart: on-failure:10
  ############################################################
  albert_mqtt:
    image: eclipse-mosquitto:latest
    volumes:
    - ./config:/mosquitto/config/
    ports: 
    - 1883:1883
    restart: on-failure:10

  albert_gateway:
    build: ./albert/gateway
    command: python3 -u gateway.py
    depends_on:
      - albert_mqtt
      - kafka
    environment:
      - BROKER=albert_mqtt
    restart: on-failure:20 #aixo abans era necessari ara crec que no ns pk

      ################################## DAKOTA  ##################################
  dakota_presence:
  # podria ficar: "build: \n\t context: users/Albert
    build: ./dakota/sensors/presence
    command: python3 -u presencesensor.py
    #maybe no fa falta depends on
    depends_on:
      - dakota_mqtt
      - kafka
    restart: on-failure:10

  dakota_temp:
    build: ./dakota/sensors/temperature
    command: python3 -u temperaturesensor.py
    depends_on:
      - dakota_mqtt
      - kafka
    restart: on-failure:10

  ###ACTUADORS:
  dakota_light:
    build: ./dakota/actuators/light
    command: python3 -u lightbulb.py
    depends_on:
      - dakota_mqtt
    restart: on-failure:10

  dakota_heat:
    build: ./dakota/actuators/heat
    command: python3 -u heatpump.py
    depends_on:
      - dakota_mqtt
    restart: on-failure:10
  ############################################################
  dakota_mqtt:
    image: eclipse-mosquitto:latest
    volumes:
    - ./config:/mosquitto/config/
    ports: 
    - 1883:1883
    restart: on-failure:10

  dakota_gateway:
    build: ./dakota/gateway
    command: python3 -u gateway.py
    depends_on:
      - dakota_mqtt
      - kafka
    environment:
      - BROKER=dakota_mqtt
    restart: on-failure:20 #aixo abans era necessari ara crec que no ns pk

          ################################## Tifany  ##################################
  tifany_presence:
  # podria ficar: "build: \n\t context: users/Albert
    build: ./tifany/sensors/presence
    command: python3 -u presencesensor.py
    #maybe no fa falta depends on
    depends_on:
      - tifany_mqtt
      - kafka
    restart: on-failure:10

  tifany_temp:
    build: ./tifany/sensors/temperature
    command: python3 -u temperaturesensor.py
    depends_on:
      - tifany_mqtt
      - kafka
    restart: on-failure:10

  ###ACTUADORS:
  tifany_light:
    build: ./tifany/actuators/light
    command: python3 -u lightbulb.py
    depends_on:
      - tifany_mqtt
    restart: on-failure:10

  tifany_heat:
    build: ./tifany/actuators/heat
    command: python3 -u heatpump.py
    depends_on:
      - tifany_mqtt
    restart: on-failure:10
  ############################################################
  tifany_mqtt:
    image: eclipse-mosquitto:latest
    volumes:
    - ./config:/mosquitto/config/
    ports: 
    - 1883:1883
    restart: on-failure:10

  tifany_gateway:
    build: ./tifany/gateway
    command: python3 -u gateway.py
    depends_on:
      - tifany_mqtt
      - kafka
    environment:
      - BROKER=tifany_mqtt
    restart: on-failure:20 #aixo abans era necessari ara crec que no ns pk

  

  #falten dos persones
  ##################################  MICROSERVEIS  ##################################

  cloud_save:
    build: ./cloud/save
    command: python3 -u save.py
    depends_on:
      - kafka
      #- albert_gateway
    restart: on-failure:10
    environment: 
      DOCKER_INFLUXDB_INIT_USERNAME: damie
      DOCKER_INFLUXDB_INIT_PASSWORD: pollagorda69 # TODO: canviar si se te por a l'exit 
      DOCKER_INFLUXDB_INIT_ORG: computacio
      DOCKER_INFLUXDB_INIT_BUCKET: computaciobucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: s2d3rf67ren42i0gg666er9
      DOCKER_INFLUXDB_HOSTNAME: influxdb
      DOCKER_INFLUXDB_PORT: 8086


  cloud_clean:
    build: ./cloud/clean
    command: python3 -u clean.py
    depends_on:
      - kafka
      #- albert_gateway
    restart: on-failure:10

  cloud_actuate:
    build: ./cloud/actuate
    command: python3 -u actuate.py 
    depends_on:
      - kafka
      - albert_mqtt
    restart: on-failure:10


  ################################## COSES DE KAFKA ##################################
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: yes 
      ADMIN_ENABLE_SERVER: no
      ZOO_LOG_LEVEL: WARN #perque calli una mica si volem tot INFO


  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092

    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT : zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      ALLOW_ANONYMOUS_LOGIN: yes
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      #TOPIC_AUTO_CREATE: False
    depends_on:
      - zookeeper
    
      ################################## INFLUXDB ##################################

  influxdb:
    image: influxdb:latest
    ports:
    - 8086:8086
    environment: 
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: damie
      DOCKER_INFLUXDB_INIT_PASSWORD: pollagorda69 # TODO: canviar si se te por a l'exit 
      DOCKER_INFLUXDB_INIT_ORG: computacio
      DOCKER_INFLUXDB_INIT_BUCKET: computaciobucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: s2d3rf67ren42i0gg666er9
      DOCKER_INFLUXDB_HOSTNAME: influxdb
      DOCKER_INFLUXDB_REPORTING_DISABLED: 'true' #potser no fan falta
      DOCKER_INFLUXDB_BIND_ADDRESS: 0.0.0.0:8086 #potser no fan falta

volumes:
  config: